name: cookster
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.12+25

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.2
  chewie: ^1.10.0
  video_player: ^2.9.3
  flutter_cache_manager: ^3.4.1
  flutter_rating_bar: ^4.0.1
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2
  image_picker: ^1.1.2
  http: ^1.3.0
  dropdown_flutter: ^1.0.1
#  timelines_plus: ^1.0.6
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  intl: ^0.20.2
#  provider:
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.5
  awesome_dialog: ^3.2.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.1
  google_places_flutter: ^2.1.0
  geolocator: ^13.0.2
  fraction: ^5.0.3
  flutter_gpu_filters_interface: ^0.0.18
  flutter_gpu_video_filters:
  videosdk: ^2.3.0
#  video_editor_2:
#  visibility_detector: ^0.4.0+2
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
#  ffmpeg_kit_flutter_new: ^1.6.1
  file_picker: ^9.1.0
  giphy_get: ^3.6.1
  permission_handler:
  flutter_swiper_plus: ^2.0.4
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  timeago: ^3.7.0
  like_button: ^2.0.5
  fluttertoast: ^8.2.12
  share_plus: ^10.1.4
  shimmer: ^3.0.0
  google_sign_in: ^6.3.0
  flutter_widget_from_html: ^0.16.0
  firebase_auth: ^5.5.1
  carousel_slider: ^5.0.0
  app_links: ^6.4.0
  flutter_facebook_auth: ^7.1.1
  wakelock_plus: ^1.2.10
  video_compress: ^3.1.4
  camera: ^0.11.1
  easy_video_editor: ^0.0.4
  pro_image_editor: ^9.2.0
  flutter_local_notifications: ^19.0.0
  photo_manager: ^3.6.4
  pinput: ^5.0.1
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.5
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  custom_info_window: ^1.0.1
  audio_waveforms: ^1.3.0
  just_waveform: ^0.0.7
  audioplayers:
  urwaypayment: ^2.0.5
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  flutter_tawkto: ^0.0.5
  googleapis_auth: ^2.0.0
  flutter_keyboard_visibility: ^6.0.0
  rxdart: ^0.27.7
  flutter_app_badge: ^2.0.2
  device_info_plus: ^11.5.0


dependency_overrides:
  device_info_plus: ^10.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/yellowLogo.png"
  adaptive_icon_background: "assets/images/yellowLogo.png"
  adaptive_icon_foreground: "assets/images/yellowLogo.png"

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/appconfig.json
    - assets/images/
    - assets/icons/
    - packages/flutter_gpu_video_filters/shaders/
    - assets/cube/
    - assets/bad_words_arabic.txt
    - assets/bad_words_english.txt



  fonts:
    - family: Lama
      fonts:
        - asset: assets/fonts/LamaRounded-Regular.ttf
        - asset: assets/fonts/LamaRounded-Medium.ttf
          weight: 400
        - asset: assets/fonts/LamaRounded-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/LamaRounded-Bold.ttf
          weight: 700
    - family: CommonFonts  # New family for the uncommented fonts
      fonts:
        - asset: assets/fonts/Arial.ttf
        - asset: assets/fonts/Courier.ttf
        - asset: assets/fonts/ComicSansMS.ttf
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
    - family: Times New Roman
      fonts:
        - asset: assets/fonts/TimesNewRoman.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    - family: Noto
      fonts:
        - asset: assets/fonts/noto.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo.ttf
    - family: Signature
      fonts:
        - asset: assets/fonts/Crustaceans-SignatureDEMO-Regular.otf
    - family: Aref
      fonts:
        - asset: assets/fonts/ArefRuqaa-Bold.ttf
