org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=false
kotlin.jvm.target.validation.mode=warning

# Enable Gradle build cache (modern way)
org.gradle.caching=true

# Enable parallel builds
org.gradle.parallel=true
org.gradle.java.home=/Users/khaled/.homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
