// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQqWRSLWguPoH27MxWSMsmVZpHvpJcI4',
    appId: '1:588874074588:android:3efcb7afd680a86f64a719',
    messagingSenderId: '588874074588',
    projectId: 'cockster-e477a',
    storageBucket: 'cockster-e477a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDww5MrJxf3eMSHXAnT-BZDp2Lc6Nxxjdg',
    appId: '1:588874074588:ios:ef6a7ce3841cae1c64a719',
    messagingSenderId: '588874074588',
    projectId: 'cockster-e477a',
    storageBucket: 'cockster-e477a.firebasestorage.app',
    androidClientId: '588874074588-5l02g7jm1srqrgve59iptcegmvnv3i6u.apps.googleusercontent.com',
    iosClientId: '588874074588-pf9i1v6e4olsrbbg5f3fgi66r983doe3.apps.googleusercontent.com',
    iosBundleId: 'com.cookster.cooksterapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz-jiPUubiZRwKkHarqJWWFEqy_wXbphU',
    appId: '1:588874074588:web:243d71c2a3596e2a64a719',
    messagingSenderId: '588874074588',
    projectId: 'cockster-e477a',
    authDomain: 'cockster-e477a.firebaseapp.com',
    storageBucket: 'cockster-e477a.firebasestorage.app',
  );

}